### ISSUE TITLE
ReadTimeOut error

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#251]
When trying to push the demo-rubygems dataset following the [README of the repo](https://github.com/meilisearch/demo-finding-rubygems), I get

```text
Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

But not in v0.20.0

**Comment by MarinPostma** [comment]
@curquiza we need a bit more context, any idea where that might be coming from?

**Comment by irevoire** [comment]
Ok, so I found the problem but have no idea how to fix it...
Basically, if we send 11 documents to transplant, it'll throw this error. And it's directly related to the size of this channel:
https://github.com/meilisearch/transplant/blob/main/meilisearch-http/src/index_controller/update_actor/store/mod.rs#L123
BUT, I can't reproduce this bug with curl
```
for i in {0..40}; do curl -X POST -H "Content-Type: application/json" --data "{\"id\": $i, \"truc\": \"hello\"}" 'http://localhost:7700/indexes/test/documents'; done
```

**Comment by curquiza** [comment]
```
curquiza ^.^ > cargo run --release
   Compiling meilisearch-http v0.21.0-alpha.6 (/Users/curquiza/Documents/transplant/meilisearch-http)
    Finished release [optimized + debuginfo] target(s) in 1m 12s
     Running `target/release/meilisearch`

888b     d888          d8b 888 d8b  .d8888b.                                    888
8888b   d8888          Y8P 888 Y8P d88P  Y88b                                   888
88888b.d88888              888     Y88b.                                        888
888Y88888P888  .d88b.  888 888 888  "Y888b.    .d88b.   8888b.  888d888 .d8888b 88888b.
888 Y888P 888 d8P  Y8b 888 888 888     "Y88b. d8P  Y8b     "88b 888P"  d88P"    888 "88b
888  Y8P  888 88888888 888 888 888       "888 88888888 .d888888 888    888      888  888
888   "   888 Y8b.     888 888 888 Y88b  d88P Y8b.     888  888 888    Y88b.    888  888
888       888  "Y8888  888 888 888  "Y8888P"   "Y8888  "Y888888 888     "Y8888P 888  888

Database path:		"./data.ms"
Server listening on:	"http://127.0.0.1:7700"
Environment:		"development"
Commit SHA:		"de9ea94f576489da7389b838b68312ab3e2598e6"
Commit date:		"2021-06-29"
Package version:	"0.21.0-alpha.6"
Anonymous telemetry:	"Disabled"

No master key found; The server will accept unidentified requests. If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY=xxx

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
Contact:		https://docs.meilisearch.com/resources/contact.html or bonjour@meilisearch.com

[2021-06-30T09:43:58Z INFO  actix_server::builder] Starting 12 workers
[2021-06-30T09:43:58Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:7700" service on 127.0.0.1:7700
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53846 "POST /indexes/rubygems/settings HTTP/1.1" 202 14 "-" "Ruby" 0.008263
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53848 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.004162
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53850 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003993
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53852 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003927
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53854 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003871
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53856 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003720
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53858 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.004217
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53860 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003818
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53862 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003742
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53864 "POST /indexes/rubygems/documents HTTP/1.1" 202 14 "-" "Ruby" 0.003733
[2021-06-30T09:44:53Z INFO  actix_web::middleware::logger] 127.0.0.1:53866 "POST /indexes/rubygems/documents HTTP/1.1" 202 15 "-" "Ruby" 0.003889
[2021-06-30T09:44:54Z INFO  actix_web::middleware::logger] 127.0.0.1:53868 "POST /indexes/rubygems/documents HTTP/1.1" 202 15 "-" "Ruby" 0.003907
[2021-06-30T09:44:54Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:44:55Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:44:56Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:44:57Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:44:58Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:00Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:01Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:03Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:05Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:07Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:09Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:12Z INFO  meilisearch_http::index::updates] document addition done: DocumentAdditionResult { nb_documents: 1800 }
[2021-06-30T09:45:12Z INFO  actix_web::middleware::logger] 127.0.0.1:53870 "POST /indexes/rubygems/documents HTTP/1.1" 202 15 "-" "Ruby" 18.259062
```

On ruby side:
```
Adding slice 0
Adding slice 1
Adding slice 2
Adding slice 3
Adding slice 4
Adding slice 5
Adding slice 6
Adding slice 7
Adding slice 8
Adding slice 9
Adding slice 10
Adding slice 11
Traceback (most recent call last):
	25: from meilisearch/app.rb:26:in `<main>'
	24: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:47:in `load_data_into_meilisearch'
	23: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:15:in `feed_meilisearch_with'
	22: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:15:in `with_index'
	21: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:15:in `each_slice'
	20: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:15:in `each'
	19: from /Users/curquiza/Documents/demo-finding-rubygems/meilisearch/feed_meilisearch.rb:17:in `block in feed_meilisearch_with'
	18: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.15.2/lib/meilisearch/index.rb:55:in `add_documents'
	17: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.15.2/lib/meilisearch/http_request.rb:29:in `http_post'
	16: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.15.2/lib/meilisearch/http_request.rb:58:in `send_request'
	15: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.15.2/lib/meilisearch/http_request.rb:30:in `block in http_post'
	14: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/httparty-0.18.1/lib/httparty.rb:524:in `post'
	13: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
	12: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
	11: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	10: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 9: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
	 8: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	 7: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	 6: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	 5: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
	 4: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
	 3: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
	 2: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
	 1: from /Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/Users/curquiza/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

**Comment by Kerollmops** [comment]
Yeah, I think @irevoire is right, I think Transplant [should not `panic/expect` when `try_send`ing in the notification channel](https://github.com/meilisearch/transplant/blob/f1cc141f6c16efab9a238a9e365a7a7bc563605e/meilisearch-http/src/index_controller/update_actor/store/mod.rs#L250), this is what triggers the TCP close on the Ruby side, what do you think?

**Comment by irevoire** [comment]
At this line, Transplant does not panic actually (as you can see in the logs, nothing happens for Transplant).
It's just waiting for a place in the channel to register its new update.
But it look like the ruby SDK doesn't want to wait and throw a timeout error right away :thinking: 
I'm not sure about this last line
